export const RMQ_CONSTANTS = {
  QUEUE: {
    CHAT: 'CHAT_QUEUE',
    USER: 'USER_QUEUE',
    NOTIFICATION: 'NOTIFICATION_QUEUE',
  },
  SERVICE: {
    CHAT: 'CHAT_SERVICE',
    USER: 'USER_SERVICE',
    NOTIFICATION: 'NOTIFICATION_SERVICE',
  },
  PATTERN: {
    SEND_CHAT: 'SEND_CHAT_PATTERN',
    VIEW_CHAT: 'VIEW_CHAT_PATTERN',
    LOGIN: 'LOGIN_PATTERN',
    REGISTER: 'REGISTER_PATTERN',
    CREATE_PROFILE_USER: 'CREATE_PROFILE_PATTERN',
    UPDATE_PROFILE_USER: 'UPDATE_PROFILE_PATTERN',
    GET_PROFILE_USER: 'GET_PROFILE_PATTERN',
    GET_ASTROLOGY: 'GET_ASTROLOGY_PATTERN',
    SEND_NOTIFICATION: 'SEND_NOTIFICATION_PATTERN',
  },
};
